///////////////////////////////////////////////////////////
//  Moteur.cs
//  Implementation of the Class Moteur
//  Generated by Enterprise Architect
//  Created on:      14-juin-2021 16:27:56
//  Original author: sophi
///////////////////////////////////////////////////////////

namespace ClassLibraryPourLaVoiture
{
    public class Moteur {

		private bool estDemarre;
		private int nbCV;



		~Moteur(){

		}

		public virtual void Dispose(){

		}

		public Moteur(){

		}

		public bool Demarrer(){

			return false;
		}

		/// 
		/// <param name="roueMotrice2"></param>
		/// <param name="roueMotrice1"></param>
		public void Entrainer(Roue roueMotrice2, Roue roueMotrice1){

		}

	}//end Moteur

}//end namespace Voiture