///////////////////////////////////////////////////////////
//  Moteur.cs
//  Implementation of the Class Moteur
//  Generated by Enterprise Architect
//  Created on:      14-juin-2021 16:27:56
//  Original author: sophi
///////////////////////////////////////////////////////////

namespace ClassLibraryPourLaVoiture
{
    public class Moteur {

		private bool estDemarre;
		private int nbCV;

        public bool EstDemarre { get => estDemarre; }
        public int NbCV { get => nbCV;}



        //Constructeur par defaut
        public Moteur()
		{
			estDemarre = false;
			nbCV = 4;

		}
		// constructeur classique
		public Moteur(bool estDeemarre, int nbCV)
		{
			this.estDemarre = estDeemarre;
			this.nbCV = nbCV;
		}
		//constructeur par recopie ou ":this(_copieMoteur.estDemarre,_copieMoteur.nbCV)"
		public Moteur(Moteur _copieMoteur)
		{
			 estDemarre=_copieMoteur.estDemarre ;
			 nbCV=_copieMoteur.nbCV ;

		}

		
		
		

		public bool Demarrer()
		{
			bool demare=true ;
            if (estDemarre==false)
            {
				estDemarre = true;
				demare = true;

			}
			return demare;
		}

		
		public void Entrainer(Roue mesRoue)
		{

		}

	}//end Moteur

}//end namespace Voiture