///////////////////////////////////////////////////////////
//  Roue.cs
//  Implementation of the Class Roue
//  Generated by Enterprise Architect
//  Created on:      14-juin-2021 16:27:54
//  Original author: sophi
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

namespace ClassLibraryPourLaVoiture
{
	public  class Roue {

		private int diametre;
        private bool tourne;

        public bool Tourne { get => tourne;  }
        public int Diametre { get => diametre; }
		//Constructeur par defaut;
        public Roue()
		{
			diametre = 16;
			tourne = false;

        }
		// constructeur classique
        public Roue(int diametre, bool tourne)
        {
            this.diametre = diametre;
            this.tourne = tourne;
        }
		//constructeur par recopie
		public Roue(Roue _copieRoue)
        {
			this.diametre = _copieRoue.diametre;
			this.tourne = _copieRoue.tourne;

		}
        
		public bool Tourner()
		{
			bool entrainDeTourner = false;
            if ( tourne== false )
            {
				tourne = true;
				entrainDeTourner = true;
            }
            else
            {
				entrainDeTourner = false;
			}

			return entrainDeTourner;
		}

	}//end Roue

}//end namespace Voiture