///////////////////////////////////////////////////////////
//  Roue.cs
//  Implementation of the Class Roue
//  Generated by Enterprise Architect
//  Created on:      14-juin-2021 16:27:54
//  Original author: sophi
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

namespace ClassLibraryPourLaVoiture
{
	public class Roue {

		private int diametre;
		private bool tourne;

		public Roue(){
			Dictionary<string, Roue> mesRoues = new Dictionary<string, Roue>();
			mesRoues.Add("roueMotriceAvtGauche", new Roue());
			mesRoues.Add("roueMotriceAvtDroite", new Roue());
			mesRoues.Add("roueArDroite", new Roue());
			mesRoues.Add("roueArGauche", new Roue());

		}

		~Roue(){

		}

		public virtual void Dispose(){

		}

		public bool Tourner(){

			return false;
		}

	}//end Roue

}//end namespace Voiture