///////////////////////////////////////////////////////////
//  Voiture.cs
//  Implementation of the Class Voiture
//  Generated by Enterprise Architect
//  Created on:      14-juin-2021 16:27:52
//  Original author: sophi
///////////////////////////////////////////////////////////





namespace ClassLibraryPourLaVoiture
{
	public class Voiture {

		private int compteurEnKM;
		private Roue sesRoues;
		private Moteur sonMoteur;
		private Roue maRoueMotriceAvantDroit;
		private Roue maRoueMotriceAvantGauche;

		public Voiture(){

		}

		~Voiture(){

		}

		public virtual void Dispose(){

		}

		public bool Arreter(){

			return true;
		}

		public bool Avancer(){

			return false;
		}

		public bool Demarrer(){

			return false;
		}

	}//end Voiture

}//end namespace Voiture