///////////////////////////////////////////////////////////
//  StadeDEvolution.cs
//  Implementation of the Class StadeDEvolution
//  Generated by Enterprise Architect
//  Created on:      09-juin-2021 11:30:11
//  Original author: kassim
///////////////////////////////////////////////////////////

using LeLepidoptere;


namespace LeLepidoptere {
	public abstract class StadeDEvolution {
		
		public StadeDEvolution()
		
		{

			

		}

		

		public abstract void SeDeplacer();
		public abstract StadeDEvolution ProchaintStade();
		
    }//end StadeDEvolution

}//end namespace Lepidoptere