///////////////////////////////////////////////////////////
//  Bouteille.cs
//  Implementation of the Class Bouteille
//  Generated by Enterprise Architect
//  Created on:      03-juin-2021 11:01:51
//  Original author: sophi
///////////////////////////////////////////////////////////




namespace CodeBouteille {
	public class Bouteille {

		private decimal contenanceEnL;
		private decimal contenuEnPourcentage;
		private bool ouvert;

		//propriétés
		public decimal ContenaceEnLitre
        {
			get { return contenanceEnL; }
            set { contenanceEnL = value; }
        }
		public decimal ContenuEnPourcentage
		{
			get { return contenuEnPourcentage; }
			set {contenuEnPourcentage = value; }
		}
		public bool Ouvert
		{
			get { return ouvert; }
			set { ouvert = value; }
		}

		// constructeur par defaut
		public Bouteille(){
			this.contenanceEnL = 0;
			this.contenuEnPourcentage = 0;
			this.ouvert = true;

		}

		public Bouteille(decimal _contenaceEnLitre,decimal _contenuEnPourcentage,bool _ouvert)
        {
			contenanceEnL = _contenaceEnLitre;
			contenuEnPourcentage = _contenuEnPourcentage;
			ouvert = _ouvert;
        }

		public void Fermer(){
            if (ouvert==true)
            {
				ouvert = false;

			}
			


			
		}

		public void Ouvrir(){
            if (ouvert==false)
            {
				ouvert = true;

            }

			
		}

		/// 
		/// <param name="aRajouterEnPourcentage"></param>
		public bool Remplir(decimal _aRajouterEnPourcentage){
            if (ouvert==true&&contenuEnPourcentage<100)
            {
                if ((_aRajouterEnPourcentage+contenuEnPourcentage)<100)
                {
					contenuEnPourcentage = _aRajouterEnPourcentage + contenuEnPourcentage;
					return true;
                }
                else
                {
					return false;
				}
				

            }
            else
            {
				return false;

			}

			
		}

		public bool RemplirTout(){

			return false;
		}

		/// 
		/// <param name="aOterEnPourcentage"></param>
		public bool Vider(decimal aOterEnPourcentage){

			return false;
		}

		public bool ViderTout(){

			return false;
		}

	}//end Bouteille

}//end namespace Bouteille