///////////////////////////////////////////////////////////
//  Case.cs
//  Implementation of the Class Case
//  Generated by Enterprise Architect
//  Created on:      12-juil.-2021 12:36:56
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




namespace JeuxEchecs {
	public class Case {

		private string saCouleur;
		private string SaPosition;

		public Case(){

		}

		~Case(){

		}

		public virtual void Dispose(){

		}

		public bool EstLibre(){

			return false;
		}

		public bool EstPleine(){

			return false;
		}

	}//end Case

}//end namespace JeuxEchecs