///////////////////////////////////////////////////////////
//  Dame.cs
//  Implementation of the Class Dame
//  Generated by Enterprise Architect
//  Created on:      12-juil.-2021 12:36:51
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




using ClassLibraryechecs;
using JeuxEchecs;
namespace JeuxEchecs {
	public class Dame : Piece {

		private string Couleur;

		public Dame(string _couleur, string _nomPiece, StruCaseCharInt _saPosition)
			: base(_couleur, _nomPiece, _saPosition)
		{

		}

		public override bool EstSurEchiquier(Case _uneCase)
		{

			return false;
		}

		public override bool Manger(){

			return false;
		}

		public override bool PeutSeDeoplacer(){

			return false;
		}

		public override bool SeDeplacer(){

			return false;
		}

		public override bool SeFaireManger(){

			return false;
		}

	}//end Dame

}//end namespace JeuxEchecs