///////////////////////////////////////////////////////////
//  Echiquier.cs
//  Implementation of the Class Echiquier
//  Generated by Enterprise Architect
//  Created on:      12-juil.-2021 12:36:50
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




using JeuxEchecs;
namespace JeuxEchecs {
	public class Echiquier {

		private List<Case> sesCases;
		private List<Piece> sesPieces;

		public Echiquier(){

		}

		~Echiquier(){

		}

		public virtual void Dispose(){

		}

		public bool Initialiser(){

			return false;
		}

		public bool SortirPiece(){

			return false;
		}

	}//end Echiquier

}//end namespace JeuxEchecs