///////////////////////////////////////////////////////////
//  Echiquier.cs
//  Implementation of the Class Echiquier
//  Generated by Enterprise Architect
//  Created on:      12-juil.-2021 12:36:50
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




using JeuxEchecs;
using System.Collections.Generic;

namespace JeuxEchecs {
	public class Echiquier {

		private Case[,] sesCases;
		private Piece[,] sesPieces;

		public Echiquier(){

		}


		

		public bool Initialiser(){

			return false;
		}

		public bool SortirPiece(){

			return false;
		}

	}//end Echiquier

}//end namespace JeuxEchecs