///////////////////////////////////////////////////////////
//  Fou.cs
//  Implementation of the Class Fou
//  Generated by Enterprise Architect
//  Created on:      12-juil.-2021 12:36:53
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




using JeuxEchecs;
namespace JeuxEchecs {
	public class Fou : Piece {

		public Fou(){

		}

		~Fou(){

		}

		public override void Dispose(){

		}

		public override bool EstSurEchiquier(){

			return false;
		}

		public override bool Manger(){

			return false;
		}

		public override bool PeutSeDeoplacer(){

			return false;
		}

		public override bool SeDeplacer(){

			return false;
		}

		public override bool SeFaireManger(){

			return false;
		}

	}//end Fou

}//end namespace JeuxEchecs