///////////////////////////////////////////////////////////
//  Fou.cs
//  Implementation of the Class Fou
//  Generated by Enterprise Architect
//  Created on:      12-juil.-2021 12:36:53
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




using ClassLibraryechecs;
using JeuxEchecs;
namespace JeuxEchecs {
	public class Fou : Piece {

		public Fou(string _couleur, string _nomPiece, StruCaseCharInt _saPosition)
			: base(_couleur, _nomPiece, _saPosition)
		{

		}

		

		

		public override bool EstSurEchiquier(Case _uneCase)
		{

			return false;
		}

		public override bool Manger(){

			return false;
		}

		public override bool PeutSeDeoplacer(){

			return false;
		}

		public override bool SeDeplacer(){

			return false;
		}

		public override bool SeFaireManger(){

			return false;
		}

	}//end Fou

}//end namespace JeuxEchecs