///////////////////////////////////////////////////////////
//  Pion.cs
//  Implementation of the Class Pion
//  Generated by Enterprise Architect
//  Created on:      12-juil.-2021 12:36:57
//  Original author: Stagiaire
///////////////////////////////////////////////////////////




using JeuxEchecs;
namespace JeuxEchecs {
	public class Pion : Piece {

		public Pion(){

		}

		public override bool EstSurEchiquier(){

			return false;
		}

		public override bool Manger(){

			return false;
		}

		public override bool PeutSeDeoplacer(){

			return false;
		}

		public override bool SeDeplacer(){

			return false;
		}

		public override bool SeFaireManger(){

			return false;
		}

	}//end Pion

}//end namespace JeuxEchecs