///////////////////////////////////////////////////////////
//  Chenille.cs
//  Implementation of the Class Chenille
//  Generated by Enterprise Architect
//  Created on:      09-juin-2021 11:30:06
//  Original author: kassim
///////////////////////////////////////////////////////////


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LeLepidoptere.LesStadeEvo;
using LeLepidoptere;
namespace LeLepidoptere.LesStadeEvo
{
	public class Chenille : StadeDEvolution {

		public Chenille(){

		}


		

		public override void  SeDeplacer(){
			Console.WriteLine("Je rampe");
		}
		public override StadeDEvolution ProchaintStade() => new Chrysalide();


	}//end Chenille

}//end namespace Lepidoptere