///////////////////////////////////////////////////////////
//  Oeuf.cs
//  Implementation of the Class Oeuf
//  Generated by Enterprise Architect
//  Created on:      09-juin-2021 11:30:10
//  Original author: kassim
///////////////////////////////////////////////////////////



using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LeLepidoptere.LesStadeEvo;
using LeLepidoptere;
namespace LeLepidoptere.LesStadeEvo
{
	public class Oeuf : StadeDEvolution {
		
		public Oeuf()
			
		
	    {
			
			
		}



		public override void SeDeplacer(){
			Console.WriteLine("Je ne sais pas me Deplacer");

		}
        public override StadeDEvolution ProchaintStade() => new Chenille();

    }//end Oeuf

}//end namespace Lepidoptere