///////////////////////////////////////////////////////////
//  Papillon.cs
//  Implementation of the Class Papillon
//  Generated by Enterprise Architect
//  Created on:      09-juin-2021 11:30:11
//  Original author: kassim
///////////////////////////////////////////////////////////




using LeLepidoptere;
using System;

namespace LeLepidoptere.LesStadeEvo
{
	public class Papillon : StadeDEvolution {

		public Papillon(){

		}


		

		public override void SeDeplacer(){
			Console.WriteLine("Je vole");
		}
		public override StadeDEvolution ProchaintStade() =>this;
	}//end Papillon

}//end namespace Lepidoptere